spring.config.import=optional:file:.env[.properties]

spring.application.name=auth0
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

spring.threads.virtual.enabled=true

server.port=${SERVER_PORT}

jwt.private-key=${JWT_PRIVATE_KEY:MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCL3zNR6LqmdXpcnqftKwSV2PIkqr97OYo0TDI/HVxavNIDT6g8IN8wsAH2xB1xEbn7yi7dmu0yf0lDOrGENpYs3cPK6mP2cqrPFucO8XYa7wEpH7jEKGN4Ip0Sr8Lrt7ESJmUEusbwZK9q17ZJnywZp8haG3kzLovJk0hGAfkL2uaJuh82CyZh6OYfU5NdKv9lA8XReiUeFJIRsXA5DK3Zj25enMhZnT4mNMHGO8On82mu2B62MY68wb33d4LhkwbLbo/tk6Ws9NX75QUT8Rwxf2RpBfdc+9c9gYYHUh6hepuZauZjNgofgzey3pZXsU+OYEqSsg6pFaZ4HzYhYol5AgMBAAECggEACCZMnLClM26z3vKlkSWJAlweG7HRL1JWcZ6g7Nl+mJDY4bWB9WLq7jDLJIAfwQdJ4VhR67qLqH4PHDouvqfZjyqqrkeC5Iig2Cka9F1wRrh3RlihUNiTlxvZMA4KmuZcjFStXR2u2rHbIKwJ5HdAQAxtGYbxRGCpZ2jL9LxHsP+NkvwFjAHVr13EN2SB2DLNfN/10gJK0OwyJLn7vyCT37kPhbmQ2O/dYwVZMPB228OoT5lLIVIBo7Fc9F4s1bhqgApIzfYGJAeSEOZqGo72Kl/DM1zOgxU/erfenDrd3N50HD0TQ2ghA+M37aP+ZU5ENnkZwBPy2rk5nOI+gjadQQKBgQC8Ag6Fd0jlVgqw+vO7AtLzKRCqS+qzC4JSgmHiJbFbfnWr/01ujDRxQGM+a4+Hy1s+avs5m5K/b0IBeRIc8SiwJXXJv/3KKO2U717qmdCpFTpxkIUBcgfVKJ2+s/bJ3iMJCMNKUppqyn5qLh2lts8VPAYwX2/ceZcWl3L8ejduKQKBgQC+dKhQO0wc9tqDxY/dZppObSDiVkEvjWzNBhE1K6NB+jqxqOH3hMFOxAwGzehZv0MwLO1wYE0nwFeATtrGdACIBxi65geNz3hQZ0zQ1UyusDPQenF7eRCY7a4oD4MDhp1DnDUASz5OHA0HHfvEU72wTLMNWYa3sC0d7rGyQ7QK0QKBgQCtIXu73lgLkQtxZPeTjIs0Dung2N49mOifEKARAELuDWtRQ15L4eLdM7zwm15mX5cbyKqmpyQhE9SFxLcwXcfpReXNLvcH9l6qmzAd/B1Rx1G1iK9i4F5kJe310oX96Yj75czpIV4/309Aek0k8E6MsGTGoOxC7Nl8nWTvKaDn2QKBgQC4tdsnNNs0nBSBB/Hm/8NXnG7wFEdUHw0OKnw13QSQ0GZsNyYwMAhqo6gmUTyvDdfTuT7uZfduPhSe09tJ7Oc3BeruGHnrBvPgxs6xGq0sHqeh4Z596YQ3TQxCvgiKOtv63lxo1JCwoHPiGyo51h16BmkA4XrOW4bmKMEd6puKgQKBgCzdmHbAdh+aPwMtlVOazdqqAxwlBw4OrD9vMyG3Zs4GQJFbQFuEcpWJzefqKIJFhe+M/kjTceu6rHi5gH/zl47ySBrU2UitW0XvjPTvwHMSXbUh/43VHKfE3Of2MlKu5Ta4h8lLVbBkapaAOVLjv731uZf2CvRNiQ9uUeNj2P1L}
jwt.public-key=${JWT_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi98zUei6pnV6XJ6n7SsEldjyJKq/ezmKNEwyPx1cWrzSA0+oPCDfMLAB9sQdcRG5+8ou3ZrtMn9JQzqxhDaWLN3Dyupj9nKqzxbnDvF2Gu8BKR+4xChjeCKdEq/C67exEiZlBLrG8GSvate2SZ8sGafIWht5My6LyZNIRgH5C9rmibofNgsmYejmH1OTXSr/ZQPF0XolHhSSEbFwOQyt2Y9uXpzIWZ0+JjTBxjvDp/NprtgetjGOvMG993eC4ZMGy26P7ZOlrPTV++UFE/EcMX9kaQX3XPvXPYGGB1IeoXqbmWrmYzYKH4M3st6WV7FPjmBKkrIOqRWmeB82IWKJeQIDAQAB}
jwt.expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}
jwt.refresh-grace-period=${JWT_REFRESH_GRACE_PERIOD}

app.cors.allowed-origins=${CORS_ORIGINS}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.database=${REDIS_DATABASE}
spring.data.redis.timeout=${REDIS_TIMEOUT}

app.policy.password-min-length=${PASSWORD_MIN_LENGTH}
app.policy.username-min-length=${USERNAME_MIN_LENGTH}
app.policy.username-max-length=${USERNAME_MAX_LENGTH}