spring.config.import=optional:file:.env[.properties]

spring.application.name=auth0
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

server.port=${SERVER_PORT}

jwt.secret=${JWT_TOKEN}
jwt.expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}
jwt.refresh-grace-period=${JWT_REFRESH_GRACE_PERIOD}

app.cors.allowed-origins=${CORS_ORIGINS}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.database=${REDIS_DATABASE}
spring.data.redis.timeout=${REDIS_TIMEOUT}

# Business Policy (Linked to .env)
app.policy.password-min-length=${PASSWORD_MIN_LENGTH}
app.policy.username-min-length=${USERNAME_MIN_LENGTH}
app.policy.username-max-length=${USERNAME_MAX_LENGTH}