spring.config.import=optional:file:.env[.properties]

spring.application.name=auth0
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

spring.threads.virtual.enabled=true

server.forwarded-headers-strategy=FRAMEWORK
server.port=${SERVER_PORT}

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.from=${MAIL_FROM}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_TLS}

jwt.private-key=${JWT_PRIVATE_KEY}
jwt.public-key=${JWT_PUBLIC_KEY}
jwt.expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}
jwt.refresh-grace-period=${JWT_REFRESH_GRACE_PERIOD}

app.cors.allowed-origins=${CORS_ORIGINS}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.database=${REDIS_DATABASE}
spring.data.redis.timeout=${REDIS_TIMEOUT}

app.policy.username-max-length=${USERNAME_MAX_LENGTH}
app.registration.otp-expiration=${OTP_EXPIRATION_SECONDS}
app.registration.stream-key=${REGISTRATION_STREAM_KEY}
app.registration.lock-prefix-email=${REGISTRATION_EMAIL_LOCK_PREFIX}
app.registration.lock-prefix-username=${REGISTRATION_USERNAME_LOCK_PREFIX}

app.password-reset.otp-expiration=${FORGOT_PASSWORD_OTP_EXPIRATION_SECONDS}
app.password-reset.stream-key=${FORGOT_PASSWORD_STREAM_KEY}
app.password-reset.lock-prefix-email=${FORGOT_PASSWORD_EMAIL_LOCK_PREFIX}
jwt.password-reset-expiration=${JWT_PASSWORD_RESET_EXPIRATION}